version: 0.2

env:
  variables:
    WORK_DIR: /home/k6/scripts
    TEST_SCRIPT: common/test.js
    TEST_REPORT_DIR: results
    PROFILE: smoke
    SCENARIO: all
    K6_DYNATRACE_DASHBOARD_ID: 1e845440-d013-4472-9d65-2ea21a5cb41a
  parameter-store:
    ACCOUNT_APP_KEY: "/perfTest/account/accounts/appKey"
    ACCOUNT_APP_PASSWORD_NEW: "/perfTest/account/testUserNewPassword"
    ACCOUNT_APP_PASSWORD: "/perfTest/account/testUserPassword"
    ACCOUNT_BASE_URL: "/perfTest/account/authentication/baseUrl"
    ACCOUNT_CURR_PHONE: "/perfTest/account/accounts/currPhone"
    ACCOUNT_EMAIL_OTP: "/perfTest/account/fixedEmailOTP"
    ACCOUNT_HOME_URL: "/perfTest/account/accounts/homeUrl"
    ACCOUNT_NEW_PHONE: "/perfTest/account/accounts/newPhone"
    ACCOUNT_PHONE_OTP: "/perfTest/account/fixedPhoneOTP"
    ACCOUNT_RP_STUB: "/perfTest/account/authentication/rpStub"
    ACCOUNT_SIGNIN_URL: "/perfTest/account/accounts/signInUrl"
    IDENTITY_ADDRESS_ENV_NAME: "/perfTest/identity/orange/addressEnvName"
    IDENTITY_ADDRESS_URL: "/perfTest/identity/orange/addressUrl"
    IDENTITY_CORE_STUB_URL: "/perfTest/identity/coreStubUrl"
    IDENTITY_CORE_URL: "/perfTest/identity/coreUrl"
    IDENTITY_DRIVING_ENDPOINT: "/perfTest/identity/lime/drivingEndpoint"
    IDENTITY_DRIVING_URL: "/perfTest/identity/lime/drivingUrl"
    IDENTITY_FRAUD_URL: "/perfTest/identity/lime/fraudUrl"
    IDENTITY_KBV_ENV_NAME: "/perfTest/identity/orange/kbvEnvName"
    IDENTITY_KBV_URL: "/perfTest/identity/orange/kbvUrl"
    IDENTITY_KBV_ANSWERS: "/perfTest/identity/orange/kbvAnswers"
    IDENTITY_KIWI_URL: "/perfTest/identity/kiwi/url"
    IDENTITY_KIWI_STUB_URL: "/perfTest/identity/kiwi/stubUrl"
    IDENTITY_KIWI_TARGET: "/perfTest/identity/kiwi/target"
    IDENTITY_ORCH_STUB_URL: "/perfTest/identity/orchStubUrl"
    IDENTITY_PASSPORT_URL: "/perfTest/identity/lime/passportUrl"
    IDENTITY_STUB_PASSWORD: "/perfTest/identity/coreStubPassword"
    IDENTITY_STUB_USERNAME: "/perfTest/identity/coreStubUsername"
    K6_DYNATRACE_APITOKEN: "/perfTest/dynatraceApiToken"
    K6_DYNATRACE_URL: "/perfTest/dynatraceUrl"
    MOBILE_BACKEND_URL: "/perfTest/mobile/backendUrl"
    MOBILE_BIOMETRIC_SESSION_ID: "/perfTest/mobile/biometricSessionID"
    MOBILE_FRONTEND_URL: "/perfTest/mobile/frontendUrl"
    MOBILE_TEST_CLIENT_EXECUTE_URL: "/perfTest/mobile/testClientUrl"
phases:
  pre_build:
    commands:
      - mkdir -p "$TEST_REPORT_DIR"
      - |
        sed -e "s#{URL}#$K6_DYNATRACE_URL#" -e "s#{APITOKEN}#$K6_DYNATRACE_APITOKEN#" -e "s#{ID}#$CODEBUILD_BUILD_ID#" $OTEL_TEMPLATE > $OTEL_CONFIG
      - /otel/otelcol-contrib  --config=$OTEL_CONFIG > otel.log 2>&1 &
  build:
    commands:
      - start=`date +"%Y-%m-%dT%H:%M:%SZ"`
      - echo "Run performance test"
      - k6 run $WORK_DIR/$TEST_SCRIPT --tag script=$TEST_SCRIPT --tag account_id=${AWS::AccountId} --out statsd
  post_build:
    commands:
      - OTEL_PID=$(pgrep /otel/otelcol-contrib)
      - kill $OTEL_PID
      - TIMEOUT=0
      - while kill -0 $OTEL_PID && (( TIMEOUT < 300 )); do sleep 1; (( TIMEOUT++ )); done
      - cat otel.log
      - ifconfig lo
      - end=`date +"%Y-%m-%dT%H:%M:%SZ"`
      - |
        echo "Dashboard link: /#dashboard;gtf="$start"%20to%20"$end";id="$K6_DYNATRACE_DASHBOARD_ID";gf=all;es=CUSTOM_DIMENSION-build_id:"$CODEBUILD_BUILD_ID
      - echo Performance test complete