AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  di-lime-performance

  Performance Testing Framework for Load Testing

Conditions:
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
  CreateVPCConfigurationForTestContainer:  !Equals [ !Ref RunTestContainerInVPC, "True" ]

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - build
      - staging
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"
  RunTestContainerInVPC:
    Description: |
      (Optional)
      Requires the testcontainers to run from within the VPC, allowing outbound configuration to be via the EIP,
      therefore allow-listable in the WAF.
      Any REGIONAL APIs under test will need to be accessible over the VPC NAT Gateway via public internet.
      Trying to communicate over a VPC endpoint for Regional API gateways results in Forbbidden 403.
    Type: "String"
    AllowedValues:
      - "True"
      - "False"
    Default: "False" # Existing behaviour is to run outside, teams need to flip this parameter to 'true' in order to benefit.
  VpcStackName:
    Type: "String"
    Description: "The name of the stack that defines the VPC to use"
    Default: "none"


Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-PerformanceTester"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      PermissionsBoundary: !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  CodeBuildServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodeBuildServicePolicy-${Environment}
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
          - Effect: "Allow"
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:*:repository/*"
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ecs:RegisterTaskDefinition
            Resource: "*"
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
            Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${LoadTestCodeBuildProject}-*"
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource: !GetAtt CodeBuildServiceRole.Arn
          - Effect: "Allow"
            Action:
              - "s3:ListAllMyBuckets"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::*"
              - !Sub "arn:${AWS::Partition}:s3:::*/*"
            Condition:
              StringEquals:
                "s3:ResourceAccount":
                  - !Sub "${AWS::AccountId}"
          - Effect: "Allow"
            Action:
              - "cloudformation:DescribeStacks"
            Resource:
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameters"
              - "ssm:GetParametersByPath"
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/perfTest/*" #Create the parameters in AWS Systems Manager Parameter store under this path
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref DynatraceAPITokenSecret
          - Effect: Allow
            Action:
              - "kms:Decrypt"
            Resource:
              - !GetAtt SecretsKmsKey.Arn

  CoreStubUserNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "IPV Core stub user name"
      Name: "/perfTest/coreStubUserName"
      Type: String
      Value: " "
      Tags:
        Name: !Join
          - "-"
          - - !Ref AWS::StackName
            - "LoadTestCodeBuildProject"
        Service: "ci/cd"
        Source: "alphagov/di-lime-performance"

  CoreStubPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "IPV Core stub password"
      Name: "/perfTest/coreStubPassword"
      Type: String
      Value: " "
      Tags:
        Name: !Join
          - "-"
          - - !Ref AWS::StackName
            - "LoadTestCodeBuildProject"
        Service: "ci/cd"
        Source: "alphagov/di-lime-performance"

  DynatraceURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: "Dynatrace URL"
      Name: "/perfTest/dynatraceUrl"
      Type: String
      Value: " "
      Tags:
        Name: !Join
          - "-"
          - - !Ref AWS::StackName
            - "LoadTestCodeBuildProject"
        Service: "ci/cd"
        Source: "alphagov/di-lime-performance"

  SecretsKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "KMS key used to protect secrets data created in ${AWS::StackName}"
      Enabled: true
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - kms:*
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - "kms:Encrypt*"
              - "kms:Decrypt*"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:Describe*"
            Resource: "*"
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/perfTest/dynatraceAPIToken"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-LoadTestCodeBuildProject"
        - Key: Service
          Value: ci/cd
        - Key: Source
          Value: alphagov/di-lime-performance

  SecretsKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-SecretsKmsKey"
      TargetKeyId: !Ref SecretsKmsKey

  DynatraceAPITokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Dynatrace API Token"
      Name: "/perfTest/dynatraceAPIToken"
      SecretString: "please-set-me"
      KmsKeyId: !GetAtt SecretsKmsKey.Arn
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-LoadTestCodeBuildProject"
        - Key: Service
          Value: ci/cd
        - Key: Source
          Value: alphagov/di-lime-performance

  VPCTestPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: CreateVPCConfigurationForTestContainer
    # checkov:skip=CKV_AWS_111:states:The mix of VPC permissions don't take a resource
    Properties:
      Roles:
        - !Ref CodeBuildServiceRole
      ManagedPolicyName:
        Fn::Join:
          - "-"
          - - !Ref AWS::StackName
            - "VPCTestPolicy"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - ec2:CreateNetworkInterface
          - ec2:DescribeDhcpOptions
          - ec2:DescribeNetworkInterfaces
          - ec2:DeleteNetworkInterface
          - ec2:DescribeSubnets
          - ec2:DescribeSecurityGroups
          - ec2:DescribeVpcs
          Resource:
          - "*"
        - Effect: Allow
          Action:
          - ec2:CreateNetworkInterfacePermission
          Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*"
          Condition:
            StringEquals:
              ec2:AuthorizedService: codebuild.amazonaws.com
            ArnEquals:
              ec2:Subnet:
                - Fn::Sub:
                  - "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${SubnetId}"
                  - SubnetId:
                      Fn::ImportValue:
                        Fn::Sub: "${VpcStackName}-ProtectedSubnetIdA"
                - Fn::Sub:
                  - "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${SubnetId}"
                  - SubnetId:
                      Fn::ImportValue:
                        Fn::Sub: "${VpcStackName}-ProtectedSubnetIdB"

  LoadTestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "LoadTest-${AWS::StackName}"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: "NO_ARTIFACTS" # Needs changing to GH in build, and promote bucket in staging.
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "CONTAINER-IMAGE-PLACEHOLDER" # Replace this with the ECR repo for this SAM container pipeline.
        ImagePullCredentialsType: "SERVICE_ROLE"
        Type: "LINUX_CONTAINER"
        VpcConfig:
          !If
          - CreateVPCConfigurationForTestContainer
          - SecurityGroupIds:
            - !GetAtt TestContainerSecurityGroup.GroupId
            Subnets:
              - Fn::ImportValue: !Sub "${VpcStackName}-ProtectedSubnetIdA"
              - Fn::ImportValue: !Sub "${VpcStackName}-ProtectedSubnetIdB"
            VpcId:
              Fn::ImportValue: !Sub "${VpcStackName}-VpcId"
          - !Ref AWS::NoValue
      TimeoutInMinutes: 480
      Source:
        Type: "NO_SOURCE"
        BuildSpec: !Sub |
          version: 0.2

          env:
            variables:
              WORK_DIR: /home/k6/scripts
              TEST_SCRIPT: test.js
              TEST_REPORT_DIR: results
              PROFILE: smoke
              SCENARIO: all
              K6_DYNATRACE_DASHBOARD_ID: 1e845440-d013-4472-9d65-2ea21a5cb41a
            parameter-store:
              CORE_STUB_USERNAME: "/perfTest/coreStubUserName"
              CORE_STUB_PASSWORD: "/perfTest/coreStubPassword"
              K6_DYNATRACE_URL: "/perfTest/dynatraceUrl"
            secrets-manager:
              K6_DYNATRACE_APITOKEN: "/perfTest/dynatraceAPIToken"

          phases:
            pre_build:
              commands:
                - mkdir -p "$TEST_REPORT_DIR"
                - |
                  sed -e "s#{URL}#$K6_DYNATRACE_URL#" -e "s#{APITOKEN}#$K6_DYNATRACE_APITOKEN#" -e "s#{ID}#$CODEBUILD_BUILD_ID#" $OTEL_TEMPLATE > $OTEL_CONFIG
                - /otel/otelcol-contrib  --config=$OTEL_CONFIG > otel.log 2>&1 &
            build:
              commands:
                - start=`date +"%Y-%m-%dT%H:%M:%SZ"`
                - echo "Run performance test"
                - k6 run $WORK_DIR/$TEST_SCRIPT --tag script=$TEST_SCRIPT --tag account_id=${AWS::AccountId} --out statsd
            post_build:
              commands:
                - end=`date +"%Y-%m-%dT%H:%M:%SZ"`
                - |
                  echo "Dashboard link: /#dashboard;gtf="$start"%20to%20"$end";id="$K6_DYNATRACE_DASHBOARD_ID";gf=all;es=CUSTOM_DIMENSION-build_id:"$CODEBUILD_BUILD_ID
                - echo Performance test complete

      Tags:
        - Key: "Name"
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "LoadTestCodeBuildProject"
        - Key: "Service"
          Value: "ci/cd"
        - Key: "Source"
          Value: "alphagov/di-lime-performance"

  TestContainerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Condition: CreateVPCConfigurationForTestContainer
    Properties:
      GroupDescription: >-
        Permits unrestricted outbound on 443 to allow the testcontainer to access VPC endpoints and outbound over SSL.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow to the wider internet on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VpcId"

Outputs:
  PerformanceRoleArn:
    Description: "The RoleArn for performance testers to trigger CodeBuild tests."
    Value: !Ref CodeBuildServiceRole
