AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  di-ipv-core-performance

  IPV Core Performance Testing Framework for Load Testing

Parameters:
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"

Conditions:
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"
Resources:

  CodeBuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Join:
          - "-"
          - - !Ref AWS::StackName
            - "CodeBuildPolicy"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Resource:
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Effect: "Allow"
          - Resource:
              - !Sub "arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/*"
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
            Effect: "Allow"
          - Resource:
              - !Sub "arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:project/LoadTest-${AWS::StackName}"
            Action:
              - "codebuild:CreateProject"
              - "codebuild:DeleteProject"
              - "codebuild:UpdateProject"
            Effect: "Allow"
          - Effect: "Allow"
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:*:repository/*"
            Sid: AllowPerfTesterEcrRepoAccess
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource:
              - "*"
            Sid: AllowPerfTesterEcrTokenAccess
          - Effect: Allow
            Action:
              - "ecs:RegisterTaskDefinition"
            Resource: "*"
            Sid: AllowPerfTesterEcsTaskDefn
          - Effect: "Allow"
            Action:
              - "ssm:GetParameters"
              - "ssm:GetParametersByPath"
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/perfTest/*" #To fetch the value of the SSM parameter created under this path
            Sid: AllowPerfTesterGetParams
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue" #pragma: allowlist secret
            Resource:
              - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/perfTest/*" # To fetch the value of the secret with this name #pragma: allowlist secret
            Sid: AllowPerfTesterGetSecret #pragma: allowlist secret


  LoadTestCodeBuildProjectServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Join:
          - "-"
          - - !Ref AWS::StackName
            - "LoadTestCodeBuildProjectServiceRole"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref CodeBuildPolicy
      PermissionsBoundary: !If
        - UsePermissionsBoundary
        - !Ref PermissionsBoundary
        - !Ref AWS::NoValue

  LoadTestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "LoadTest-${AWS::StackName}"
      ServiceRole: !Ref LoadTestCodeBuildProjectServiceRole
      Artifacts:
        Type: "NO_ARTIFACTS" # Needs changing to GH in build, and promote bucket in staging.
      Environment:
        ComputeType: "BUILD_GENERAL1_LARGE"
        Image: "CONTAINER-IMAGE-PLACEHOLDER" # Replace this with the ECR repo for this SAM container pipeline.
        ImagePullCredentialsType: "SERVICE_ROLE"
        Type: "LINUX_CONTAINER"
      TimeoutInMinutes: 480
      Source:
        Type: "NO_SOURCE"
        BuildSpec: !Sub |
          version: 0.2

          env:
            variables:
              WORK_DIR: /home/k6/scripts
              TEST_SCRIPT: test.js
              TEST_REPORT_DIR: results
              PROFILE: smoke
              SCENARIO: all
              ORCH_STUB_URL: Orchestrator Stub URL
              CORE_URL: IPV Core test environment URL
              K6_DYNATRACE_DASHBOARD_ID: 1e845440-d013-4472-9d65-2ea21a5cb41a
            parameter-store:
              K6_DYNATRACE_URL: "/perfTest/dynatraceUrl"
            secrets-manager:
              K6_DYNATRACE_APITOKEN: "/perfTest/dynatraceAPIToken"

          phases:
            pre_build:
              commands:
                - mkdir -p "$TEST_REPORT_DIR"
                - |
                  sed -e "s#{URL}#$K6_DYNATRACE_URL#" -e "s#{APITOKEN}#$K6_DYNATRACE_APITOKEN#" -e "s#{ID}#$CODEBUILD_BUILD_ID#" $OTEL_TEMPLATE > $OTEL_CONFIG
                - /otel/otelcol-contrib  --config=$OTEL_CONFIG > otel.log 2>&1 &
            build:
              commands:
                - start=`date +"%Y-%m-%dT%H:%M:%SZ"`
                - echo "Run performance test"
                - k6 run $WORK_DIR/$TEST_SCRIPT --tag script=$TEST_SCRIPT --tag account_id=${AWS::AccountId} --out statsd
            post_build:
              commands:
                - end=`date +"%Y-%m-%dT%H:%M:%SZ"`
                - |
                  echo "Dashboard link: /#dashboard;gtf="$start"%20to%20"$end";id="$K6_DYNATRACE_DASHBOARD_ID";gf=all;es=CUSTOM_DIMENSION-build_id:"$CODEBUILD_BUILD_ID
<<<<<<< HEAD
            post_build:
              commands:
                - cat otel.log
=======
>>>>>>> upstream/main
                - echo Performance test complete

      Tags:
        - Key: "Name"
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "LoadTestCodeBuildProject"
        - Key: "Service"
          Value: "ci/cd"
        - Key: "Source"
          Value: "alphagov/di-ipv-core-performance"

Outputs:
  PerformanceRoleArn:
    Description: "The RoleArn for performance testers to trigger CodeBuild tests."
    Value: !Sub "${AWS::Region}-ipv-core-performance-tester"
