AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  di-devplatform-performance

  Performance Testing Framework for Load Testing

Conditions:
  UsePermissionsBoundary:
    Fn::Not:
      - Fn::Equals:
          - !Ref PermissionsBoundary
          - "none"

Parameters:
  Environment:
    Description: "The name of the environment to deploy to"
    Type: "String"
    AllowedValues:
      - dev
      - build
      - staging
      - production
  PermissionsBoundary:
    Description: "The ARN of the permissions boundary to apply when creating IAM roles"
    Type: String
    Default: "none"
  VpcStackName:
    Type: "String"
    Description: "The name of the stack that defines the VPC to use"
    Default: "none"

Mappings:
  BTM:
    AWS:
      AccountID: "716404857987"
  SPOT:
    AWS:
      AccountID: "429671060046"
  ContraIndicators:
    AWS:
      AccountID: "755415363251"
  TxMA:
    AWS:
      AccountID: "750703655225"
  IPVR:
    AWS:
      AccountID: "073717171046"

Resources:
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-PerformanceServiceRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  CodeBuildServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-CodeBuildServicePolicy-${Environment}
      Roles:
        - !Ref CodeBuildServiceRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource:
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
              - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:*"
          - Effect: "Allow"
            Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:BatchGetImage"
              - "ecr:GetDownloadUrlForLayer"
            Resource:
              - !Sub "arn:${AWS::Partition}:ecr:${AWS::Region}:*:repository/*"
          - Effect: "Allow"
            Action:
              - "ecr:GetAuthorizationToken"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ecs:RegisterTaskDefinition
            Resource: "*"
          - Effect: Allow
            Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
            Resource: !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${LoadTestCodeBuildProject}-*"
          - Effect: Allow
            Action:
              - iam:PassRole
              - sts:AssumeRole
            Resource: !GetAtt CodeBuildServiceRole.Arn
          - Effect: "Allow"
            Action:
              - "s3:ListAllMyBuckets"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::*"
              - !Sub "arn:${AWS::Partition}:s3:::*/*"
            Condition:
              StringEquals:
                "s3:ResourceAccount":
                  - !Sub "${AWS::AccountId}"
          - Effect: "Allow"
            Action:
              - "s3:PutObject"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${AWS::StackName}-test-results*"
          - Effect: "Allow"
            Action:
              - "cloudformation:DescribeStacks"
            Resource:
              - !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*/*"
          - Effect: "Allow"
            Action:
              - "ssm:GetParameters"
              - "ssm:GetParametersByPath"
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/perfTest/*" #Create the parameters in AWS Systems Manager Parameter store under this path

  PerformanceTesterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-PerformanceTesterRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !GetAtt CodeBuildServiceRole.Arn
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              ArnLike:
                "aws:PrincipalArn":
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/${AWS::Region}/AWSReservedSSO_di-perf-test-prod-admin_*" # Prod Admin Control Tower Role
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/${AWS::Region}/AWSReservedSSO_di-perf-test-prod-poweruser_*" # Prod Power User Control Tower Role
                  - !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-reserved/sso.amazonaws.com/${AWS::Region}/AWSReservedSSO_di-perf-test-prod-testers_*" # Prod Tester Control Tower Role
      PermissionsBoundary:
        !If [
          UsePermissionsBoundary,
          !Ref PermissionsBoundary,
          !Ref AWS::NoValue,
        ]

  PerformanceTesterPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${AWS::StackName}-PerformanceTesterPolicy-${Environment}
      Roles:
        - !Ref PerformanceTesterRole
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: "Allow"
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource:
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}"
                    - !FindInMap [BTM, AWS, AccountID]
                    - "key/*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}"
                    - !FindInMap [SPOT, AWS, AccountID]
                    - "key/*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}"
                    - !FindInMap [TxMA, AWS, AccountID]
                    - "key/*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:kms:${AWS::Region}"
                    - !FindInMap [IPVR, AWS, AccountID]
                    - "key/*"
          - Effect: "Allow"
            Action:
              - "sqs:SendMessage"
              - "sqs:ReceiveMessage"
              - "sqs:GetQueueAttributes"
              - "sqs:DeleteMessage"
              - "sqs:ChangeMessageVisibility"
            Resource:
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}"
                    - !FindInMap [BTM, AWS, AccountID]
                    - "di-btm-*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}"
                    - !FindInMap [SPOT, AWS, AccountID]
                    - "di-ipv-spot-app-*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}"
                    - !FindInMap [TxMA, AWS, AccountID]
                    - "event-processing-*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:sqs:${AWS::Region}"
                    - !FindInMap [IPVR, AWS, AccountID]
                    - "ipvreturn-*"
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
            Resource:
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}"
                    - !FindInMap [SPOT, AWS, AccountID]
                    - "function:*"
              - Fn::Join:
                  - ":"
                  - - !Sub "arn:${AWS::Partition}:lambda:${AWS::Region}"
                    - !FindInMap [ContraIndicators, AWS, AccountID]
                    - "function:*"

  VPCTestPolicy:
    Type: AWS::IAM::ManagedPolicy
    # checkov:skip=CKV_AWS_111:states:The mix of VPC permissions don't take a resource
    Properties:
      Roles:
        - !Ref CodeBuildServiceRole
      ManagedPolicyName:
        Fn::Join:
          - "-"
          - - !Ref AWS::StackName
            - "VPCTestPolicy"
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - "/"
                            - Ref: AWS::StackId
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeDhcpOptions
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
              - ec2:DescribeSubnets
              - ec2:DescribeSecurityGroups
              - ec2:DescribeVpcs
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterfacePermission
            Resource: !Sub "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*"
            Condition:
              StringEquals:
                ec2:AuthorizedService: codebuild.amazonaws.com
              ArnEquals:
                ec2:Subnet:
                  - Fn::Sub:
                      - "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${SubnetId}"
                      - SubnetId:
                          Fn::ImportValue:
                            Fn::Sub: "${VpcStackName}-ProtectedSubnetIdA"
                  - Fn::Sub:
                      - "arn:${AWS::Partition}:ec2:${AWS::Region}:${AWS::AccountId}:subnet/${SubnetId}"
                      - SubnetId:
                          Fn::ImportValue:
                            Fn::Sub: "${VpcStackName}-ProtectedSubnetIdB"

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName:
        Fn::Join:
          - "-"
          - - Ref: AWS::StackName
            - test-results
            - Fn::Select:
                - 4
                - Fn::Split:
                    - "-"
                    - Fn::Select:
                        - 2
                        - Fn::Split:
                            - /
                            - Ref: AWS::StackId
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 365
            Status: Enabled
      LoggingConfiguration:
        LogFilePrefix: ""
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  LoadTestCodeBuildProject:
    Type: AWS::CodeBuild::Project
    DependsOn: VPCTestPolicy
    Properties:
      Name: !Sub "LoadTest-${AWS::StackName}"
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: "NO_ARTIFACTS" # Needs changing to GH in build, and promote bucket in staging.
      Environment:
        ComputeType: "BUILD_GENERAL1_LARGE"
        Image: "CONTAINER-IMAGE-PLACEHOLDER" # Replace this with the ECR repo for this SAM container pipeline.
        ImagePullCredentialsType: "SERVICE_ROLE"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value: !Ref ResultsBucket
          - Name: EXECUTION_ROLE
            Type: PLAINTEXT
            Value: !GetAtt PerformanceTesterRole.Arn
          - Name: TEST_SCRIPT
            Type: PLAINTEXT
            Value: common/test.js
          - Name: PROFILE
            Type: PLAINTEXT
            Value: smoke
          - Name: SCENARIO
            Type: PLAINTEXT
            Value: all
          - Name: ENVIRONMENT
            Type: PLAINTEXT
            Value: build
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt TestContainerSecurityGroup.GroupId
        Subnets:
          - Fn::ImportValue: !Sub "${VpcStackName}-ProtectedSubnetIdA"
          - Fn::ImportValue: !Sub "${VpcStackName}-ProtectedSubnetIdB"
        VpcId:
          Fn::ImportValue: !Sub "${VpcStackName}-VpcId"
      TimeoutInMinutes: 480
      Source:
        Type: "NO_SOURCE"
        BuildSpec: |
          version: 0.2

          env:
            variables:
              WORK_DIR: /home/k6/scripts
              REPORTING_DIR: /home/k6/reporting
              JSON_RESULTS: results.gz
              K6_DYNATRACE_DASHBOARD_ID: 1e845440-d013-4472-9d65-2ea21a5cb41a
              SLACK_NOTIFY_CHANNEL: C05J07H48UE
            parameter-store:
              ACCOUNT_APP_KEY: "/perfTest/account/accounts/appKey"
              ACCOUNT_APP_PASSWORD_NEW: "/perfTest/account/testUserNewPassword"
              ACCOUNT_APP_PASSWORD: "/perfTest/account/testUserPassword"
              ACCOUNT_BRAVO_ID_REUSE_API_KEY: "/perfTest/account/bravo/idReuseApiKey"
              ACCOUNT_BRAVO_ID_REUSE_API_KEY_SUMMARISE: "/perfTest/account/bravo/idReuseApiKeySummarise"
              ACCOUNT_BRAVO_ID_REUSE_MOCK: "/perfTest/account/bravo/idReuseMock"
              ACCOUNT_BRAVO_ID_REUSE_URL: "/perfTest/account/bravo/idReuseUrl"
              ACCOUNT_CURR_PHONE: "/perfTest/account/accounts/currPhone"
              ACCOUNT_EMAIL_OTP: "/perfTest/account/fixedEmailOTP"
              ACCOUNT_HOME_URL: "/perfTest/account/accounts/homeUrl"
              ACCOUNT_NEW_PHONE: "/perfTest/account/accounts/newPhone"
              ACCOUNT_PHONE_OTP: "/perfTest/account/fixedPhoneOTP"
              ACCOUNT_RP_STUB: "/perfTest/account/authentication/rpStub"
              ACCOUNT_SIGNIN_URL: "/perfTest/account/accounts/signInUrl"
              DATA_BTM_SQS: "/perfTest/data/btm/perfSQS"
              DATA_TXMA_SQS: "/perfTest/data/txma/perfSQS"
              DATA_BTM_SQS_PAYLOAD_EVENTS: "/perfTest/data/txma/SQSPayloadEvents"
              IDENTITY_ADDRESS_URL: "/perfTest/identity/orange/addressUrl"
              IDENTITY_CORE_STUB_URL: "/perfTest/identity/coreStubUrl"
              IDENTITY_CORE_URL: "/perfTest/identity/coreUrl"
              IDENTITY_DRIVING_URL: "/perfTest/identity/lime/drivingUrl"
              IDENTITY_FRAUD_URL: "/perfTest/identity/lime/fraudUrl"
              IDENTITY_KBV_URL: "/perfTest/identity/orange/kbvUrl"
              IDENTITY_KBV_ANSWERS: "/perfTest/identity/orange/kbvAnswers"
              IDENTITY_KIWI_CIC_STUB_URL: "/perfTest/identity/kiwi/cic/stubUrl"
              IDENTITY_KIWI_CIC_TARGET: "/perfTest/identity/kiwi/cic/target"
              IDENTITY_KIWI_F2F_STUB_URL: "/perfTest/identity/kiwi/f2f/stubUrl"
              IDENTITY_KIWI_F2F_TARGET: "/perfTest/identity/kiwi/f2f/target"
              IDENTITY_KIWI_STUB_SQS: "/perfTest/identity/kiwi/stubTxMAConsumer"
              IDENTITY_ORCH_STUB_URL: "/perfTest/identity/orchStubUrl"
              IDENTITY_PASSPORT_URL: "/perfTest/identity/lime/passportUrl"
              IDENTITY_SPOT_SQS: "/perfTest/identity/spot/SQS"
              IDENTITY_STUB_PASSWORD: "/perfTest/identity/coreStubPassword"
              IDENTITY_STUB_USERNAME: "/perfTest/identity/coreStubUsername"
              K6_DYNATRACE_APITOKEN: "/perfTest/dynatraceApiToken"
              K6_DYNATRACE_URL: "/perfTest/dynatraceUrl"
              MOBILE_BACKEND_URL: "/perfTest/mobile/backendUrl"
              MOBILE_FRONTEND_URL: "/perfTest/mobile/frontendUrl"
              MOBILE_TEST_CLIENT_EXECUTE_URL: "/perfTest/mobile/testClientUrl"
              SLACK_OAUTH_TOKEN: "/perfTest/slack/OAuthToken"
          phases:
            pre_build:
              commands:
                - |
                  sed -e "s#{URL}#$K6_DYNATRACE_URL#" -e "s#{APITOKEN}#$K6_DYNATRACE_APITOKEN#" -e "s#{ID}#$CODEBUILD_BUILD_NUMBER#" $OTEL_TEMPLATE > $OTEL_CONFIG
                - /otel/otelcol-contrib  --config=$OTEL_CONFIG > otel.log 2>&1 &
                - export EXECUTION_CREDENTIALS=$(aws sts assume-role --role-arn $EXECUTION_ROLE --role-session-name $CODEBUILD_BUILD_NUMBER)
                - source ${REPORTING_DIR}/slack.sh POST
            build:
              commands:
                - echo "Run performance test"
                - k6 run $WORK_DIR/$TEST_SCRIPT --tag script=$TEST_SCRIPT --tag account_id=$AWS_ACCOUNT_ID --out output-statsd --out json=$JSON_RESULTS
            post_build:
              commands:
                - echo "Uploading test results to s3"
                - S3_LOCATION=s3://${S3_BUCKET}/${TEST_SCRIPT%.*}/$(date +%F/%T)
                - aws s3 cp $JSON_RESULTS ${S3_LOCATION}/$JSON_RESULTS
                - echo "Shutting down OpenTelemetry collector"
                - sleep 120
                - OTEL_PID=$(pgrep /otel/otelcol-contrib)
                - kill $OTEL_PID
                - TIMEOUT=0
                - while kill -0 $OTEL_PID && (( TIMEOUT < 300 )); do sleep 1; (( TIMEOUT++ )); done
                - source ${REPORTING_DIR}/slack.sh UPDATE
                - echo "Performance test complete"

      Tags:
        - Key: "Name"
          Value: !Join
            - "-"
            - - !Ref AWS::StackName
              - "LoadTestCodeBuildProject"
        - Key: "Service"
          Value: "ci/cd"
        - Key: "Source"
          Value: "alphagov/di-devplatform-performance"

  TestContainerSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: >-
        Permits unrestricted outbound on 443 to allow the testcontainer to access VPC endpoints and outbound over SSL.
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          Description: Allow to the wider internet on port 443
          FromPort: 443
          IpProtocol: tcp
          ToPort: 443
      VpcId:
        Fn::ImportValue: !Sub "${VpcStackName}-VpcId"

Outputs:
  PerformanceRoleArn:
    Description: "The RoleArn for performance testers to trigger CodeBuild tests."
    Value: !Ref CodeBuildServiceRole
