AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  perf-rp-stub

  Sample SAM Template for perf-rp-stub

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
    Environment:
      Variables:
        TABLE_NAME: !Ref SessionTable
  Api:
    TracingEnabled: true
  
Resources:
  StartFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rp-stub/
      Handler: start.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: start
          POWERTOOLS_METRICS_NAMESPACE: perf-rp-stub
          LOG_LEVEL: INFO
      Events:
        start:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /start
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - start.ts
    Connectors:
      SessionsTableConnection:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Write
  CallbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: rp-stub/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: callback
          POWERTOOLS_METRICS_NAMESPACE: perf-rp-stub
          LOG_LEVEL: INFO
      Events:
        callback:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /callback
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        # Sourcemap: true # Enabling source maps will create the required NODE_OPTIONS environment variables on your lambda function during sam build
        EntryPoints:
        - callback.ts
    Connectors:
      SessionsTableConnection:
        Properties:
          Destination:
            Id: SessionTable
          Permissions:
            - Read
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-SessionTable"
      AttributeDefinitions:
        - AttributeName: Session
          AttributeType: S
      KeySchema:
        - AttributeName: Session
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ExpiryTime
        Enabled: True
  

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RpStubApi:
    Description: API Gateway endpoint URL for Prod stage for RP Stub Functions
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  StartkFunction:
    Description: Start Lambda Function ARN
    Value: !GetAtt StartFunction.Arn
  StartFunctionIamRole:
    Description: Implicit IAM Role created for Callback function
    Value: !GetAtt StartFunctionRole.Arn
  CallbackFunction:
    Description: Callback Lambda Function ARN
    Value: !GetAtt CallbackFunction.Arn
  CallbackFunctionIamRole:
    Description: Implicit IAM Role created for Callback function
    Value: !GetAtt CallbackFunctionRole.Arn
