name: Koa Stub Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "koa-stub/**"

jobs:
  run-unit-tests:
    permissions:
      id-token: write
      contents: read
    name: Lint and Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: koa-stub/
    steps:
      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true

      - name: Setup nodeJS v20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: koa-stub/src/

      - name: Run eslint
        run: npm run lint
        working-directory: koa-stub/src/

      - name: Run unit tests
        run: npm run test
        working-directory: koa-stub/src/
  sam-validate:
    permissions:
      id-token: write
      contents: read
    name: SAM Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: koa-stub/
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.PERF_STUB_GH_ACTIONS_ROLE_ARN }}

      - name: Check out repository code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true

      - name: Setup nodeJS v20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@342dcc4899c07fedf41f91cbb1e6c68925a85d37 # v2

      - name: SAM Validate
        run: |
          echo "SAM_CLI_TELEMETRY=0" >> $GITHUB_ENV
          sam validate --lint
      - name: SAM Build
        run: |
          sam build
      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@f906dab69fb3b4847aa10cd910317bfe564ebcf9 # v3.9
        with:
          artifact-bucket-name: ${{ secrets.PERF_STUB_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.PERF_STUB_SIGNING_PROFILE_NAME }}
          working-directory: ./koa-stub/.aws-sam/build
