name: Publish

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./deploy

jobs:
  dockerBuildAndPush:
    name: Docker build and push
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Deploy SAM app to Fraud ECR
        uses: alphagov/di-devplatform-upload-action-ecr@1.0.2
        with:
          artifact-bucket-name: ${{ secrets.ARTIFACT_SOURCE_BUCKET_NAME }}
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY }}
          working-directory: ./deploy
          template-file: template.yaml
          role-to-assume-arn: ${{ secrets.GH_ACTIONS_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY }}
      - name: Deploy SAM app to DL ECR
        uses: alphagov/di-devplatform-upload-action-ecr@1.0.2
        with:
          artifact-bucket-name: ${{ secrets.DL_ARTIFACT_SOURCE_BUCKET_NAME }}
          container-sign-kms-key-arn: ${{ secrets.DL_CONTAINER_SIGN_KMS_KEY }}
          working-directory: ./deploy
          template-file: template.yaml
          role-to-assume-arn: ${{ secrets.DL_GH_ACTIONS_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.DL_ECR_REPOSITORY }}
