name: Pre-Merge Lint & Unit Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'koa-stub/**'
  merge_group:
  workflow_dispatch:


defaults:
  run:
    shell: bash
    working-directory: ./deploy/scripts

jobs:
  k6_unit_test:
    name: Run linting and unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: '0'

      - name: Install dependencies
        run: npm i

      - name: Run linting checks
        run: npm run lint

      - name: Transpile TypeScript test scripts
        run: npm start

      - name: Run local k6 unit test script
        uses: grafana/k6-action@e4714b734f2b0afaabeb7b4a69142745548ab9ec # v0.3.1
        with:
          filename: ./deploy/scripts/dist/common/unit-tests.js

      - run: git fetch origin main
      - name:  Run pre-commit action
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --from-ref FETCH_HEAD --to-ref HEAD
